장애물 추가
CSID-DGU/2020-2-OSSP-CP-OldKokiri-6 pull request #37
Opened 2020-12-05 12:29 UTC by kiho7248

불타는 선인장 추가시켰습니다.

2020-12-06 09:23 UTC, good-riverdeer requested changes
일반 선인장과 불 선인장이 같은 빈도로 나오게 되니까 너무 많이 나오게 되는 것 같습니다.
불 선인장의 빈도를 조금 줄여주시기 바랍니다

2020-12-06 11:00 UTC, good-riverdeer commented on main.py
> +                        last_obstacle.add(fire_Cactus(gamespeed, object_size[0], object_size[1]))
`len(fire_cacti) == 0.5`를 만족하는 경우는 없어서 이 분기는 필요없는 분기인 것 같습니다.

2020-12-06 13:06 UTC, kiho7248 commented
반영했습니다

2020-12-06 13:24 UTC, good-riverdeer approved these changes
넵 고생하셨습니다!

2020-12-06 15:16 UTC, epsltm09 approved these changes

2020-12-07 04:02 UTC, kimbk209 approved these changes

2020-12-07 04:03 UTC, merged